
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Feb 13 2026 16:15:26 CST (Feb 13 2026 22:15:26 UTC)

// Verification Directory fv/banyan8x8 

module banyan8x8(in, sel_s1, sel_s2, sel_s3, out);
  input [7:0] in;
  input [3:0] sel_s1, sel_s2, sel_s3;
  output [7:0] out;
  wire [7:0] in;
  wire [3:0] sel_s1, sel_s2, sel_s3;
  wire [7:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27;
  INV_X16M_A12TS_C40 g1021(.A (n_19), .Y (out[5]));
  INV_X16M_A12TS_C40 g1019(.A (n_26), .Y (out[6]));
  INV_X16M_A12TS_C40 g1018(.A (n_25), .Y (out[2]));
  INV_X16M_A12TS_C40 g1029(.A (n_11), .Y (out[3]));
  INV_X16M_A12TS_C40 g1027(.A (n_15), .Y (out[0]));
  INV_X16M_A12TS_C40 g1020(.A (n_24), .Y (out[7]));
  INV_X16M_A12TS_C40 g1026(.A (n_27), .Y (out[4]));
  INV_X16M_A12TS_C40 g1028(.A (n_20), .Y (out[1]));
  AOI22_X0P7M_A12TS_C40 g1030__2398(.A0 (n_16), .A1 (n_17), .B0 (n_18),
       .B1 (sel_s3[2]), .Y (n_27));
  AOI22_X0P7M_A12TS_C40 g1023__5107(.A0 (n_21), .A1 (n_22), .B0 (n_23),
       .B1 (sel_s3[3]), .Y (n_26));
  AOI22_X0P7M_A12TS_C40 g1022__6260(.A0 (n_8), .A1 (n_9), .B0 (n_10),
       .B1 (sel_s3[1]), .Y (n_25));
  AOI22_X0P7M_A12TS_C40 g1024__4319(.A0 (n_23), .A1 (n_22), .B0 (n_21),
       .B1 (sel_s3[3]), .Y (n_24));
  AOI22_X0P7M_A12TS_C40 g1032__8428(.A0 (n_12), .A1 (n_13), .B0 (n_14),
       .B1 (sel_s3[0]), .Y (n_20));
  AOI22_X0P7M_A12TS_C40 g1025__5526(.A0 (n_18), .A1 (n_17), .B0 (n_16),
       .B1 (sel_s3[2]), .Y (n_19));
  AOI22_X0P7M_A12TS_C40 g1031__6783(.A0 (n_14), .A1 (n_13), .B0 (n_12),
       .B1 (sel_s3[0]), .Y (n_15));
  AOI22_X0P7M_A12TS_C40 g1033__3680(.A0 (n_10), .A1 (n_9), .B0 (n_8),
       .B1 (sel_s3[1]), .Y (n_11));
  MXIT2_X0P5M_A12TS_C40 g1036__1617(.A (n_2), .B (n_3), .S0
       (sel_s2[2]), .Y (n_10));
  MXIT2_X0P5M_A12TS_C40 g1035__2802(.A (n_0), .B (n_1), .S0
       (sel_s2[0]), .Y (n_14));
  MXIT2_X0P5M_A12TS_C40 g1034__1705(.A (n_6), .B (n_7), .S0
       (sel_s2[1]), .Y (n_21));
  MXIT2_X0P5M_A12TS_C40 g1037__5122(.A (n_4), .B (n_5), .S0
       (sel_s2[3]), .Y (n_23));
  MXIT2_X0P5M_A12TS_C40 g1040__8246(.A (n_7), .B (n_6), .S0
       (sel_s2[1]), .Y (n_16));
  MXIT2_X0P5M_A12TS_C40 g1039__7098(.A (n_5), .B (n_4), .S0
       (sel_s2[3]), .Y (n_18));
  MXIT2_X0P5M_A12TS_C40 g1038__6131(.A (n_3), .B (n_2), .S0
       (sel_s2[2]), .Y (n_12));
  MXIT2_X0P5M_A12TS_C40 g1041__1881(.A (n_1), .B (n_0), .S0
       (sel_s2[0]), .Y (n_8));
  MXIT2_X0P5M_A12TS_C40 g1047__5115(.A (in[4]), .B (in[5]), .S0
       (sel_s1[2]), .Y (n_1));
  MXIT2_X0P5M_A12TS_C40 g1046__7482(.A (in[0]), .B (in[1]), .S0
       (sel_s1[0]), .Y (n_0));
  MXIT2_X0P5M_A12TS_C40 g1045__4733(.A (in[1]), .B (in[0]), .S0
       (sel_s1[0]), .Y (n_7));
  MXIT2_X0P5M_A12TS_C40 g1049__6161(.A (in[5]), .B (in[4]), .S0
       (sel_s1[2]), .Y (n_6));
  MXIT2_X0P5M_A12TS_C40 g1043__9315(.A (in[6]), .B (in[7]), .S0
       (sel_s1[3]), .Y (n_2));
  MXIT2_X0P5M_A12TS_C40 g1042__9945(.A (in[7]), .B (in[6]), .S0
       (sel_s1[3]), .Y (n_4));
  MXIT2_X0P5M_A12TS_C40 g1048__2883(.A (in[3]), .B (in[2]), .S0
       (sel_s1[1]), .Y (n_5));
  MXIT2_X0P5M_A12TS_C40 g1044__2346(.A (in[2]), .B (in[3]), .S0
       (sel_s1[1]), .Y (n_3));
  INV_X0P5B_A12TS_C40 g1052(.A (sel_s3[0]), .Y (n_13));
  INV_X0P5B_A12TS_C40 g1053(.A (sel_s3[2]), .Y (n_17));
  INV_X0P5B_A12TS_C40 g1050(.A (sel_s3[3]), .Y (n_22));
  INV_X0P5B_A12TS_C40 g1051(.A (sel_s3[1]), .Y (n_9));
endmodule

