
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Feb 25 2026 14:03:54 CST (Feb 25 2026 20:03:54 UTC)

// Verification Directory fv/fifo 

module fifo(clk, rst_n, w_en, data_in, full, r_en, data_out, empty);
  input clk, rst_n, w_en, r_en;
  input [7:0] data_in;
  output full, empty;
  output [7:0] data_out;
  wire clk, rst_n, w_en, r_en;
  wire [7:0] data_in;
  wire full, empty;
  wire [7:0] data_out;
  wire [3:0] count;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[5] ;
  wire [2:0] r_ptr;
  wire [2:0] w_ptr;
  wire \data_out[0]_252 , \data_out[1]_253 , \data_out[2]_254 ,
       \data_out[3]_255 , \data_out[4]_256 , \data_out[5]_257 ,
       \data_out[6]_258 , \data_out[7]_259 ;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_9, n_10;
  wire n_11, n_12, n_16, n_18, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_30, n_31, n_32;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_231, n_242, n_253, n_264, n_275, n_286, n_297;
  wire n_308;
  DFFRPQ_X1M_A12TS_C40 data_out_reg_6_(.R (n_130), .CK (clk), .D
       (n_129), .Q (\data_out[6]_258 ));
  DFFRPQ_X1M_A12TS_C40 data_out_reg_0_(.R (n_130), .CK (clk), .D
       (n_128), .Q (\data_out[0]_252 ));
  DFFRPQ_X1M_A12TS_C40 data_out_reg_2_(.R (n_130), .CK (clk), .D
       (n_127), .Q (\data_out[2]_254 ));
  DFFRPQ_X1M_A12TS_C40 data_out_reg_4_(.R (n_130), .CK (clk), .D
       (n_121), .Q (\data_out[4]_256 ));
  DFFRPQ_X1M_A12TS_C40 data_out_reg_1_(.R (n_130), .CK (clk), .D
       (n_125), .Q (\data_out[1]_253 ));
  DFFRPQ_X1M_A12TS_C40 data_out_reg_7_(.R (n_130), .CK (clk), .D
       (n_122), .Q (\data_out[7]_259 ));
  DFFRPQ_X1M_A12TS_C40 data_out_reg_5_(.R (n_130), .CK (clk), .D
       (n_123), .Q (\data_out[5]_257 ));
  OAI211_X0P5M_A12TS_C40 g4350__2398(.A0 (n_126), .A1 (n_11), .B0
       (n_87), .C0 (n_116), .Y (n_129));
  OAI211_X0P5M_A12TS_C40 g4354__5107(.A0 (n_124), .A1 (n_9), .B0
       (n_72), .C0 (n_117), .Y (n_128));
  OAI211_X0P5M_A12TS_C40 g4355__6260(.A0 (n_126), .A1 (n_12), .B0
       (n_73), .C0 (n_118), .Y (n_127));
  DFFRPQ_X1M_A12TS_C40 data_out_reg_3_(.R (n_130), .CK (clk), .D
       (n_120), .Q (\data_out[3]_255 ));
  OAI211_X0P5M_A12TS_C40 g4344__4319(.A0 (n_124), .A1 (n_0), .B0
       (n_88), .C0 (n_112), .Y (n_125));
  OAI211_X0P5M_A12TS_C40 g4347__8428(.A0 (n_126), .A1 (n_3), .B0
       (n_92), .C0 (n_114), .Y (n_123));
  OAI211_X0P5M_A12TS_C40 g4343__5526(.A0 (n_124), .A1 (n_16), .B0
       (n_81), .C0 (n_111), .Y (n_122));
  OAI211_X0P5M_A12TS_C40 g4348__6783(.A0 (n_126), .A1 (n_1), .B0
       (n_70), .C0 (n_113), .Y (n_121));
  DFFRPQN_X1M_A12TS_C40 count_reg_2_(.R (n_130), .CK (clk), .D (n_119),
       .QN (count[2]));
  OAI211_X0P5M_A12TS_C40 g4349__3680(.A0 (n_126), .A1 (n_4), .B0
       (n_74), .C0 (n_109), .Y (n_120));
  OAI211_X0P5M_A12TS_C40 g4351__1617(.A0 (n_103), .A1 (count[2]), .B0
       (n_42), .C0 (n_56), .Y (n_119));
  AOI21_X0P5M_A12TS_C40 g4365__2802(.A0 (\mem[2] [2]), .A1 (n_108), .B0
       (n_104), .Y (n_118));
  AOI21_X0P5M_A12TS_C40 g4366__1705(.A0 (\mem[3] [0]), .A1 (n_115), .B0
       (n_106), .Y (n_117));
  AOI21_X0P5M_A12TS_C40 g4357__5122(.A0 (\mem[3] [6]), .A1 (n_115), .B0
       (n_107), .Y (n_116));
  AOI211_X0P7M_A12TS_C40 g4359__8246(.A0 (n_115), .A1 (\mem[3] [5]),
       .B0 (n_91), .C0 (n_94), .Y (n_114));
  AOI211_X0P7M_A12TS_C40 g4360__7098(.A0 (n_115), .A1 (\mem[3] [4]),
       .B0 (n_93), .C0 (n_96), .Y (n_113));
  AOI211_X0P7M_A12TS_C40 g4362__6131(.A0 (n_110), .A1 (\mem[6] [1]),
       .B0 (n_77), .C0 (n_99), .Y (n_112));
  AOI211_X0P7M_A12TS_C40 g4358__1881(.A0 (n_110), .A1 (\mem[6] [7]),
       .B0 (n_85), .C0 (n_98), .Y (n_111));
  SDFFRPQNL_X1M_A12TS_C40 count_reg_1_(.R (n_130), .CK (clk), .D
       (n_102), .SI (count[1]), .SE (n_101), .QN (count[1]));
  DFFRPQN_X1M_A12TS_C40 count_reg_3_(.R (n_130), .CK (clk), .D (n_100),
       .QN (count[3]));
  AOI211_X0P7M_A12TS_C40 g4361__5115(.A0 (n_108), .A1 (\mem[2] [3]),
       .B0 (n_79), .C0 (n_78), .Y (n_109));
  OAI211_X0P5M_A12TS_C40 g4363__7482(.A0 (n_105), .A1 (n_18), .B0
       (n_68), .C0 (n_76), .Y (n_107));
  OAI211_X0P5M_A12TS_C40 g4381__4733(.A0 (n_105), .A1 (n_10), .B0
       (n_53), .C0 (n_75), .Y (n_106));
  OAI211_X0P5M_A12TS_C40 g4384__6161(.A0 (n_105), .A1 (n_5), .B0
       (n_52), .C0 (n_71), .Y (n_104));
  OA21_X0P7M_A12TS_C40 g4364__9315(.A0 (n_58), .A1 (n_102), .B0
       (n_101), .Y (n_103));
  AO21A1AI2_X0P7M_A12TS_C40 g4356__9945(.A0 (n_39), .A1 (n_83), .B0
       (count[3]), .C0 (n_54), .Y (n_100));
  AO21B_X0P5M_A12TS_C40 g4382__2883(.A0 (n_97), .A1 (\mem[0] [1]), .B0N
       (n_64), .Y (n_99));
  AO21B_X0P5M_A12TS_C40 g4383__2346(.A0 (n_97), .A1 (\mem[0] [7]), .B0N
       (n_59), .Y (n_98));
  AO21B_X0P5M_A12TS_C40 g4385__1666(.A0 (n_97), .A1 (\mem[0] [4]), .B0N
       (n_67), .Y (n_96));
  SDFFQL_X1M_A12TS_C40 mem_reg_0__0_(.CK (clk), .D (\mem[0] [0]), .SI
       (n_231), .SE (n_95), .Q (\mem[0] [0]));
  SDFFQL_X1M_A12TS_C40 mem_reg_0__6_(.CK (clk), .D (\mem[0] [6]), .SI
       (n_253), .SE (n_95), .Q (\mem[0] [6]));
  SDFFQL_X1M_A12TS_C40 mem_reg_0__1_(.CK (clk), .D (\mem[0] [1]), .SI
       (n_308), .SE (n_95), .Q (\mem[0] [1]));
  AO21B_X0P5M_A12TS_C40 g4386__7410(.A0 (n_97), .A1 (\mem[0] [5]), .B0N
       (n_65), .Y (n_94));
  SDFFQL_X1M_A12TS_C40 mem_reg_0__3_(.CK (clk), .D (\mem[0] [3]), .SI
       (n_286), .SE (n_95), .Q (\mem[0] [3]));
  SDFFQL_X1M_A12TS_C40 mem_reg_0__4_(.CK (clk), .D (\mem[0] [4]), .SI
       (n_275), .SE (n_95), .Q (\mem[0] [4]));
  SDFFQL_X1M_A12TS_C40 mem_reg_0__5_(.CK (clk), .D (\mem[0] [5]), .SI
       (n_264), .SE (n_95), .Q (\mem[0] [5]));
  SDFFQL_X1M_A12TS_C40 mem_reg_0__7_(.CK (clk), .D (\mem[0] [7]), .SI
       (n_242), .SE (n_95), .Q (\mem[0] [7]));
  SDFFQL_X1M_A12TS_C40 mem_reg_0__2_(.CK (clk), .D (\mem[0] [2]), .SI
       (n_297), .SE (n_95), .Q (\mem[0] [2]));
  AO22_X0P7M_A12TS_C40 g4436__6417(.A0 (n_90), .A1 (\mem[4] [4]), .B0
       (n_89), .B1 (\mem[7] [4]), .Y (n_93));
  AOI22_X0P7M_A12TS_C40 g4434__5477(.A0 (n_86), .A1 (\mem[1] [5]), .B0
       (n_110), .B1 (\mem[6] [5]), .Y (n_92));
  AO22_X0P7M_A12TS_C40 g4433__2398(.A0 (n_90), .A1 (\mem[4] [5]), .B0
       (n_89), .B1 (\mem[7] [5]), .Y (n_91));
  AOI22_X0P7M_A12TS_C40 g4432__5107(.A0 (n_80), .A1 (\mem[5] [1]), .B0
       (n_115), .B1 (\mem[3] [1]), .Y (n_88));
  AOI22_X0P7M_A12TS_C40 g4430__6260(.A0 (n_86), .A1 (\mem[1] [6]), .B0
       (n_110), .B1 (\mem[6] [6]), .Y (n_87));
  AO22_X0P7M_A12TS_C40 g4429__4319(.A0 (n_90), .A1 (\mem[4] [7]), .B0
       (n_89), .B1 (\mem[7] [7]), .Y (n_85));
  SDFFQL_X1M_A12TS_C40 mem_reg_3__1_(.CK (clk), .D (\mem[3] [1]), .SI
       (n_308), .SE (n_84), .Q (\mem[3] [1]));
  SDFFQL_X1M_A12TS_C40 mem_reg_3__4_(.CK (clk), .D (\mem[3] [4]), .SI
       (n_275), .SE (n_84), .Q (\mem[3] [4]));
  SDFFQL_X1M_A12TS_C40 mem_reg_3__7_(.CK (clk), .D (\mem[3] [7]), .SI
       (n_242), .SE (n_84), .Q (\mem[3] [7]));
  SDFFQL_X1M_A12TS_C40 mem_reg_3__6_(.CK (clk), .D (\mem[3] [6]), .SI
       (n_253), .SE (n_84), .Q (\mem[3] [6]));
  SDFFQL_X1M_A12TS_C40 mem_reg_3__5_(.CK (clk), .D (\mem[3] [5]), .SI
       (n_264), .SE (n_84), .Q (\mem[3] [5]));
  OA21_X0P7M_A12TS_C40 g4392__8428(.A0 (n_57), .A1 (count[0]), .B0
       (n_83), .Y (n_101));
  SDFFQL_X1M_A12TS_C40 mem_reg_2__1_(.CK (clk), .D (n_308), .SI
       (\mem[2] [1]), .SE (n_82), .Q (\mem[2] [1]));
  SDFFQL_X1M_A12TS_C40 mem_reg_3__3_(.CK (clk), .D (\mem[3] [3]), .SI
       (n_286), .SE (n_84), .Q (\mem[3] [3]));
  SDFFQL_X1M_A12TS_C40 mem_reg_3__2_(.CK (clk), .D (\mem[3] [2]), .SI
       (n_297), .SE (n_84), .Q (\mem[3] [2]));
  SDFFQL_X1M_A12TS_C40 mem_reg_3__0_(.CK (clk), .D (\mem[3] [0]), .SI
       (n_231), .SE (n_84), .Q (\mem[3] [0]));
  SDFFQL_X1M_A12TS_C40 mem_reg_2__7_(.CK (clk), .D (n_242), .SI
       (\mem[2] [7]), .SE (n_82), .Q (\mem[2] [7]));
  SDFFQL_X1M_A12TS_C40 mem_reg_2__6_(.CK (clk), .D (n_253), .SI
       (\mem[2] [6]), .SE (n_82), .Q (\mem[2] [6]));
  SDFFQL_X1M_A12TS_C40 mem_reg_2__4_(.CK (clk), .D (n_275), .SI
       (\mem[2] [4]), .SE (n_82), .Q (\mem[2] [4]));
  SDFFQL_X1M_A12TS_C40 mem_reg_2__2_(.CK (clk), .D (n_297), .SI
       (\mem[2] [2]), .SE (n_82), .Q (\mem[2] [2]));
  SDFFQL_X1M_A12TS_C40 mem_reg_2__3_(.CK (clk), .D (n_286), .SI
       (\mem[2] [3]), .SE (n_82), .Q (\mem[2] [3]));
  AOI22_X0P7M_A12TS_C40 g4446__5526(.A0 (n_80), .A1 (\mem[5] [7]), .B0
       (n_115), .B1 (\mem[3] [7]), .Y (n_81));
  AO22_X0P7M_A12TS_C40 g4440__6783(.A0 (n_90), .A1 (\mem[4] [3]), .B0
       (n_89), .B1 (\mem[7] [3]), .Y (n_79));
  AO21B_X0P5M_A12TS_C40 g4380__3680(.A0 (n_97), .A1 (\mem[0] [3]), .B0N
       (n_51), .Y (n_78));
  AO22_X0P7M_A12TS_C40 g4442__1617(.A0 (n_90), .A1 (\mem[4] [1]), .B0
       (n_89), .B1 (\mem[7] [1]), .Y (n_77));
  AOI22_X0P7M_A12TS_C40 g4443__2802(.A0 (n_97), .A1 (\mem[0] [6]), .B0
       (n_89), .B1 (\mem[7] [6]), .Y (n_76));
  AOI22_X0P7M_A12TS_C40 g4438__1705(.A0 (n_97), .A1 (\mem[0] [0]), .B0
       (n_110), .B1 (\mem[6] [0]), .Y (n_75));
  AOI22_X0P7M_A12TS_C40 g4447__5122(.A0 (n_86), .A1 (\mem[1] [3]), .B0
       (n_115), .B1 (\mem[3] [3]), .Y (n_74));
  AOI22_X0P7M_A12TS_C40 g4448__8246(.A0 (n_86), .A1 (\mem[1] [2]), .B0
       (n_115), .B1 (\mem[3] [2]), .Y (n_73));
  AOI22_X0P7M_A12TS_C40 g4450__7098(.A0 (n_108), .A1 (\mem[2] [0]), .B0
       (n_80), .B1 (\mem[5] [0]), .Y (n_72));
  AOI22_X0P7M_A12TS_C40 g4451__6131(.A0 (n_97), .A1 (\mem[0] [2]), .B0
       (n_110), .B1 (\mem[6] [2]), .Y (n_71));
  AOI22_X0P7M_A12TS_C40 g4437__1881(.A0 (n_86), .A1 (\mem[1] [4]), .B0
       (n_110), .B1 (\mem[6] [4]), .Y (n_70));
  SDFFQL_X1M_A12TS_C40 mem_reg_2__0_(.CK (clk), .D (n_231), .SI
       (\mem[2] [0]), .SE (n_82), .Q (\mem[2] [0]));
  SDFFQL_X1M_A12TS_C40 mem_reg_1__2_(.CK (clk), .D (n_297), .SI
       (\mem[1] [2]), .SE (n_69), .Q (\mem[1] [2]));
  SDFFQL_X1M_A12TS_C40 mem_reg_1__0_(.CK (clk), .D (n_231), .SI
       (\mem[1] [0]), .SE (n_69), .Q (\mem[1] [0]));
  SDFFQL_X1M_A12TS_C40 mem_reg_1__1_(.CK (clk), .D (n_308), .SI
       (\mem[1] [1]), .SE (n_69), .Q (\mem[1] [1]));
  SDFFQL_X1M_A12TS_C40 mem_reg_1__3_(.CK (clk), .D (n_286), .SI
       (\mem[1] [3]), .SE (n_69), .Q (\mem[1] [3]));
  SDFFQL_X1M_A12TS_C40 mem_reg_1__4_(.CK (clk), .D (n_275), .SI
       (\mem[1] [4]), .SE (n_69), .Q (\mem[1] [4]));
  SDFFQL_X1M_A12TS_C40 mem_reg_1__5_(.CK (clk), .D (n_264), .SI
       (\mem[1] [5]), .SE (n_69), .Q (\mem[1] [5]));
  SDFFQL_X1M_A12TS_C40 mem_reg_1__6_(.CK (clk), .D (n_253), .SI
       (\mem[1] [6]), .SE (n_69), .Q (\mem[1] [6]));
  SDFFQL_X1M_A12TS_C40 mem_reg_1__7_(.CK (clk), .D (n_242), .SI
       (\mem[1] [7]), .SE (n_69), .Q (\mem[1] [7]));
  SDFFQL_X1M_A12TS_C40 mem_reg_2__5_(.CK (clk), .D (n_264), .SI
       (\mem[2] [5]), .SE (n_82), .Q (\mem[2] [5]));
  AOI22_X0P7M_A12TS_C40 g4444__5115(.A0 (n_108), .A1 (\mem[2] [6]), .B0
       (n_66), .B1 (\data_out[6]_258 ), .Y (n_68));
  AOI22_X0P7M_A12TS_C40 g4435__7482(.A0 (n_108), .A1 (\mem[2] [4]), .B0
       (n_66), .B1 (\data_out[4]_256 ), .Y (n_67));
  AOI22_X0P7M_A12TS_C40 g4431__4733(.A0 (n_108), .A1 (\mem[2] [5]), .B0
       (n_66), .B1 (\data_out[5]_257 ), .Y (n_65));
  AOI22_X0P7M_A12TS_C40 g4445__6161(.A0 (n_108), .A1 (\mem[2] [1]), .B0
       (n_66), .B1 (\data_out[1]_253 ), .Y (n_64));
  SDFFQL_X1M_A12TS_C40 mem_reg_5__0_(.CK (clk), .D (\mem[5] [0]), .SI
       (n_231), .SE (n_63), .Q (\mem[5] [0]));
  SDFFQL_X1M_A12TS_C40 mem_reg_5__2_(.CK (clk), .D (\mem[5] [2]), .SI
       (n_297), .SE (n_63), .Q (\mem[5] [2]));
  SDFFQL_X1M_A12TS_C40 mem_reg_7__5_(.CK (clk), .D (\mem[7] [5]), .SI
       (n_264), .SE (n_61), .Q (\mem[7] [5]));
  SDFFQL_X1M_A12TS_C40 mem_reg_5__7_(.CK (clk), .D (\mem[5] [7]), .SI
       (n_242), .SE (n_63), .Q (\mem[5] [7]));
  SDFFQL_X1M_A12TS_C40 mem_reg_4__5_(.CK (clk), .D (\mem[4] [5]), .SI
       (n_264), .SE (n_60), .Q (\mem[4] [5]));
  SDFFQL_X1M_A12TS_C40 mem_reg_5__6_(.CK (clk), .D (\mem[5] [6]), .SI
       (n_253), .SE (n_63), .Q (\mem[5] [6]));
  SDFFQL_X1M_A12TS_C40 mem_reg_6__5_(.CK (clk), .D (\mem[6] [5]), .SI
       (n_264), .SE (n_62), .Q (\mem[6] [5]));
  SDFFQL_X1M_A12TS_C40 mem_reg_6__7_(.CK (clk), .D (\mem[6] [7]), .SI
       (n_242), .SE (n_62), .Q (\mem[6] [7]));
  SDFFQL_X1M_A12TS_C40 mem_reg_7__1_(.CK (clk), .D (\mem[7] [1]), .SI
       (n_308), .SE (n_61), .Q (\mem[7] [1]));
  SDFFQL_X1M_A12TS_C40 mem_reg_5__5_(.CK (clk), .D (\mem[5] [5]), .SI
       (n_264), .SE (n_63), .Q (\mem[5] [5]));
  SDFFQL_X1M_A12TS_C40 mem_reg_5__3_(.CK (clk), .D (\mem[5] [3]), .SI
       (n_286), .SE (n_63), .Q (\mem[5] [3]));
  SDFFQL_X1M_A12TS_C40 mem_reg_4__2_(.CK (clk), .D (\mem[4] [2]), .SI
       (n_297), .SE (n_60), .Q (\mem[4] [2]));
  SDFFQL_X1M_A12TS_C40 mem_reg_5__4_(.CK (clk), .D (\mem[5] [4]), .SI
       (n_275), .SE (n_63), .Q (\mem[5] [4]));
  SDFFQL_X1M_A12TS_C40 mem_reg_5__1_(.CK (clk), .D (\mem[5] [1]), .SI
       (n_308), .SE (n_63), .Q (\mem[5] [1]));
  SDFFQL_X1M_A12TS_C40 mem_reg_4__0_(.CK (clk), .D (\mem[4] [0]), .SI
       (n_231), .SE (n_60), .Q (\mem[4] [0]));
  AOI22_X0P7M_A12TS_C40 g4449__9315(.A0 (n_108), .A1 (\mem[2] [7]), .B0
       (n_66), .B1 (\data_out[7]_259 ), .Y (n_59));
  SDFFQL_X1M_A12TS_C40 mem_reg_6__3_(.CK (clk), .D (\mem[6] [3]), .SI
       (n_286), .SE (n_62), .Q (\mem[6] [3]));
  SDFFQL_X1M_A12TS_C40 mem_reg_4__1_(.CK (clk), .D (\mem[4] [1]), .SI
       (n_308), .SE (n_60), .Q (\mem[4] [1]));
  SDFFQL_X1M_A12TS_C40 mem_reg_4__3_(.CK (clk), .D (\mem[4] [3]), .SI
       (n_286), .SE (n_60), .Q (\mem[4] [3]));
  SDFFQL_X1M_A12TS_C40 mem_reg_6__0_(.CK (clk), .D (\mem[6] [0]), .SI
       (n_231), .SE (n_62), .Q (\mem[6] [0]));
  SDFFQL_X1M_A12TS_C40 mem_reg_4__4_(.CK (clk), .D (\mem[4] [4]), .SI
       (n_275), .SE (n_60), .Q (\mem[4] [4]));
  SDFFQL_X1M_A12TS_C40 mem_reg_4__7_(.CK (clk), .D (\mem[4] [7]), .SI
       (n_242), .SE (n_60), .Q (\mem[4] [7]));
  SDFFQL_X1M_A12TS_C40 mem_reg_4__6_(.CK (clk), .D (\mem[4] [6]), .SI
       (n_253), .SE (n_60), .Q (\mem[4] [6]));
  SDFFQL_X1M_A12TS_C40 mem_reg_6__2_(.CK (clk), .D (\mem[6] [2]), .SI
       (n_297), .SE (n_62), .Q (\mem[6] [2]));
  SDFFQL_X1M_A12TS_C40 mem_reg_6__1_(.CK (clk), .D (\mem[6] [1]), .SI
       (n_308), .SE (n_62), .Q (\mem[6] [1]));
  SDFFQL_X1M_A12TS_C40 mem_reg_6__4_(.CK (clk), .D (\mem[6] [4]), .SI
       (n_275), .SE (n_62), .Q (\mem[6] [4]));
  SDFFQL_X1M_A12TS_C40 mem_reg_6__6_(.CK (clk), .D (\mem[6] [6]), .SI
       (n_253), .SE (n_62), .Q (\mem[6] [6]));
  SDFFQL_X1M_A12TS_C40 mem_reg_7__0_(.CK (clk), .D (\mem[7] [0]), .SI
       (n_231), .SE (n_61), .Q (\mem[7] [0]));
  SDFFQL_X1M_A12TS_C40 mem_reg_7__2_(.CK (clk), .D (\mem[7] [2]), .SI
       (n_297), .SE (n_61), .Q (\mem[7] [2]));
  SDFFQL_X1M_A12TS_C40 mem_reg_7__3_(.CK (clk), .D (\mem[7] [3]), .SI
       (n_286), .SE (n_61), .Q (\mem[7] [3]));
  SDFFQL_X1M_A12TS_C40 mem_reg_7__4_(.CK (clk), .D (\mem[7] [4]), .SI
       (n_275), .SE (n_61), .Q (\mem[7] [4]));
  SDFFQL_X1M_A12TS_C40 mem_reg_7__7_(.CK (clk), .D (\mem[7] [7]), .SI
       (n_242), .SE (n_61), .Q (\mem[7] [7]));
  SDFFQL_X1M_A12TS_C40 mem_reg_7__6_(.CK (clk), .D (\mem[7] [6]), .SI
       (n_253), .SE (n_61), .Q (\mem[7] [6]));
  SDFFRPQNL_X1M_A12TS_C40 count_reg_0_(.R (n_130), .CK (clk), .D
       (n_58), .SI (n_57), .SE (n_46), .QN (count[0]));
  AOI22BB_X0P7M_A12TS_C40 g4463__9945(.A0 (n_66), .A1 (n_58), .B0N
       (n_58), .B1N (n_55), .Y (n_83));
  INV_X0P5B_A12TS_C40 g4478(.A (n_86), .Y (n_124));
  NAND4_X0P7M_A12TS_C40 g4387__2883(.A (n_57), .B (n_55), .C (n_102),
       .D (count[2]), .Y (n_56));
  NAND4BB_X0P5M_A12TS_C40 g4441__2346(.AN (n_58), .BN (n_20), .C
       (n_55), .D (count[3]), .Y (n_54));
  AOI22_X0P7M_A12TS_C40 g4467__1666(.A0 (n_89), .A1 (\mem[7] [0]), .B0
       (n_66), .B1 (\data_out[0]_252 ), .Y (n_53));
  AOI22_X0P7M_A12TS_C40 g4466__7410(.A0 (n_89), .A1 (\mem[7] [2]), .B0
       (n_66), .B1 (\data_out[2]_254 ), .Y (n_52));
  INV_X0P5B_A12TS_C40 g4469(.A (n_126), .Y (n_80));
  INV_X0P5B_A12TS_C40 g4468(.A (n_105), .Y (n_90));
  AOI22_X0P7M_A12TS_C40 g4439__6417(.A0 (n_110), .A1 (\mem[6] [3]), .B0
       (n_66), .B1 (\data_out[3]_255 ), .Y (n_51));
  NOR2_X0P5M_A12TS_C40 g4481__5477(.A (n_50), .B (r_ptr[0]), .Y (n_86));
  NOR3BB_X0P7M_A12TS_C40 g4484__2398(.AN (n_47), .BN (w_ptr[0]), .C
       (w_ptr[1]), .Y (n_95));
  NOR2_X1B_A12TS_C40 g4482__5107(.A (n_50), .B (n_48), .Y (n_97));
  NAND2_X0P5A_A12TS_C40 g4475__6260(.A (n_49), .B (r_ptr[0]), .Y
       (n_105));
  NAND2_X0P5A_A12TS_C40 g4476__4319(.A (n_49), .B (n_48), .Y (n_126));
  NOR3BB_X0P7M_A12TS_C40 g4480__8428(.AN (n_45), .BN (r_ptr[1]), .C
       (n_48), .Y (n_108));
  NOR2B_X1M_A12TS_C40 g4490__5526(.AN (n_47), .B (n_43), .Y (n_84));
  NAND2_X0P5M_A12TS_C40 g4494__6783(.A (n_47), .B (n_23), .Y (n_82));
  NAND2_X0P5M_A12TS_C40 g4495__3680(.A (n_47), .B (n_22), .Y (n_69));
  ADDH_X1M_A12TS_C40 g4470__1617(.A (n_66), .B (n_6), .CO (n_55), .S
       (n_46));
  SDFFRPQL_X1M_A12TS_C40 w_ptr_reg_2_(.R (n_130), .CK (clk), .D (n_30),
       .SI (w_ptr[2]), .SE (n_58), .Q (w_ptr[2]));
  SDFFRPQL_X1M_A12TS_C40 r_ptr_reg_2_(.R (n_130), .CK (clk), .D (n_35),
       .SI (r_ptr[2]), .SE (n_66), .Q (r_ptr[2]));
  SDFFRPQNL_X1M_A12TS_C40 w_ptr_reg_0_(.R (n_130), .CK (clk), .D
       (n_58), .SI (n_57), .SE (w_ptr[0]), .QN (w_ptr[0]));
  SDFFRPQL_X1M_A12TS_C40 w_ptr_reg_1_(.R (n_130), .CK (clk), .D (n_27),
       .SI (w_ptr[1]), .SE (n_58), .Q (w_ptr[1]));
  SDFFRPQL_X1M_A12TS_C40 r_ptr_reg_1_(.R (n_130), .CK (clk), .D (n_24),
       .SI (r_ptr[1]), .SE (n_66), .Q (r_ptr[1]));
  NOR3_X1M_A12TS_C40 g4485__2802(.A (n_44), .B (w_ptr[1]), .C (n_21),
       .Y (n_60));
  NAND2XB_X0P5M_A12TS_C40 g4492__1705(.A (n_45), .BN (r_ptr[1]), .Y
       (n_50));
  SDFFRPQNL_X1M_A12TS_C40 r_ptr_reg_0_(.R (n_130), .CK (clk), .D
       (n_66), .SI (n_41), .SE (r_ptr[0]), .QN (r_ptr[0]));
  NOR2B_X0P5M_A12TS_C40 g4487__5122(.AN (n_45), .B (n_36), .Y (n_115));
  NOR2_X1B_A12TS_C40 g4493__8246(.A (n_44), .B (n_25), .Y (n_62));
  NOR2_X1B_A12TS_C40 g4496__7098(.A (n_44), .B (n_26), .Y (n_63));
  NOR2_X1B_A12TS_C40 g4489__6131(.A (n_44), .B (n_43), .Y (n_61));
  AO21A1AI2_X0P7M_A12TS_C40 g4479__1881(.A0 (n_38), .A1 (n_41), .B0
       (n_37), .C0 (n_58), .Y (n_42));
  NOR2_X0P5M_A12TS_C40 g4486__5115(.A (n_40), .B (r_ptr[1]), .Y (n_49));
  NOR3BB_X0P7M_A12TS_C40 g4483__7482(.AN (r_ptr[0]), .BN (r_ptr[1]), .C
       (n_40), .Y (n_110));
  OA22_X0P7M_A12TS_C40 g4491__4733(.A0 (n_57), .A1 (n_38), .B0 (n_58),
       .B1 (n_37), .Y (n_39));
  NOR3_X0P5M_A12TS_C40 g4500__6161(.A (w_ptr[2]), .B (n_58), .C
       (n_130), .Y (n_47));
  NOR2_X1B_A12TS_C40 g4488__9315(.A (n_40), .B (n_36), .Y (n_89));
  NOR2_X0P5M_A12TS_C40 g4498__9945(.A (n_66), .B (r_ptr[2]), .Y (n_45));
  NAND3_X0P7M_A12TS_C40 g4501__2883(.A (w_ptr[2]), .B (n_57), .C
       (rst_n), .Y (n_44));
  NAND2_X0P5M_A12TS_C40 g4497__2346(.A (n_41), .B (r_ptr[2]), .Y
       (n_40));
  INV_X0P6M_A12TS_C40 g4502(.A (n_41), .Y (n_66));
  INV_X0P6B_A12TS_C40 g4504(.A (n_57), .Y (n_58));
  NOR2B_X0P5M_A12TS_C40 g4503__1666(.AN (r_en), .B (n_34), .Y (n_41));
  NOR2B_X0P5M_A12TS_C40 g4505__7410(.AN (w_en), .B (n_31), .Y (n_57));
  XNOR2_X1M_A12TS_C40 g4499__6417(.A (n_36), .B (r_ptr[2]), .Y (n_35));
  INV_X0P5B_A12TS_C40 g4506(.A (n_32), .Y (n_34));
  INV_X16M_A12TS_C40 g4507(.A (n_32), .Y (empty));
  INV_X0P5B_A12TS_C40 g4509(.A (n_28), .Y (n_31));
  XNOR2_X1M_A12TS_C40 g4511__5477(.A (n_43), .B (w_ptr[2]), .Y (n_30));
  INV_X16M_A12TS_C40 g4510(.A (n_28), .Y (full));
  NAND2_X0P5A_A12TS_C40 g4508__2398(.A (n_38), .B (count[3]), .Y
       (n_32));
  NAND2XB_X0P5M_A12TS_C40 g4512__5107(.A (n_38), .BN (count[3]), .Y
       (n_28));
  NAND2_X0P5A_A12TS_C40 g4513__6260(.A (n_26), .B (n_25), .Y (n_27));
  OA21_X0P7M_A12TS_C40 g4514__4319(.A0 (n_48), .A1 (r_ptr[1]), .B0
       (n_36), .Y (n_24));
  INV_X0P5B_A12TS_C40 g4516(.A (n_25), .Y (n_23));
  INV_X0P5B_A12TS_C40 g4519(.A (n_22), .Y (n_26));
  NAND2_X0P5A_A12TS_C40 g4518__8428(.A (w_ptr[1]), .B (n_21), .Y
       (n_43));
  INV_X0P5B_A12TS_C40 g4520(.A (n_37), .Y (n_20));
  NOR3BB_X0P7M_A12TS_C40 g4515__5526(.AN (count[0]), .BN (count[2]), .C
       (n_102), .Y (n_38));
  NAND2_X0P5A_A12TS_C40 g4523__6783(.A (n_48), .B (r_ptr[1]), .Y
       (n_36));
  NOR2_X0P5M_A12TS_C40 g4521__3680(.A (w_ptr[1]), .B (w_ptr[0]), .Y
       (n_22));
  NOR2_X0P5M_A12TS_C40 g4522__1617(.A (count[1]), .B (count[2]), .Y
       (n_37));
  NAND2_X0P5A_A12TS_C40 g4517__2802(.A (w_ptr[0]), .B (w_ptr[1]), .Y
       (n_25));
  BUF_X16M_A12TS_C40 g4543(.A (\data_out[7]_259 ), .Y (data_out[7]));
  INV_X0P5B_A12TS_C40 g4539(.A (\mem[4] [6]), .Y (n_18));
  BUF_X16M_A12TS_C40 g4535(.A (\data_out[4]_256 ), .Y (data_out[4]));
  INV_X0P5B_A12TS_C40 g4541(.A (\mem[1] [7]), .Y (n_16));
  BUF_X16M_A12TS_C40 g4531(.A (\data_out[6]_258 ), .Y (data_out[6]));
  BUF_X16M_A12TS_C40 g4528(.A (\data_out[3]_255 ), .Y (data_out[3]));
  BUF_X16M_A12TS_C40 g4527(.A (\data_out[0]_252 ), .Y (data_out[0]));
  INV_X0P5B_A12TS_C40 g4529(.A (\mem[5] [2]), .Y (n_12));
  INV_X0P5B_A12TS_C40 g4544(.A (\mem[5] [6]), .Y (n_11));
  INV_X0P5B_A12TS_C40 g4546(.A (w_ptr[0]), .Y (n_21));
  INV_X0P5B_A12TS_C40 g4532(.A (count[1]), .Y (n_102));
  INV_X0P5B_A12TS_C40 g4533(.A (r_ptr[0]), .Y (n_48));
  INV_X0P5B_A12TS_C40 g4538(.A (\mem[4] [0]), .Y (n_10));
  INV_X0P5B_A12TS_C40 g4524(.A (\mem[1] [0]), .Y (n_9));
  BUF_X16M_A12TS_C40 g4525(.A (\data_out[1]_253 ), .Y (data_out[1]));
  BUF_X16M_A12TS_C40 g4540(.A (\data_out[2]_254 ), .Y (data_out[2]));
  INV_X0P5B_A12TS_C40 g4545(.A (count[0]), .Y (n_6));
  INV_X0P5B_A12TS_C40 g4530(.A (\mem[4] [2]), .Y (n_5));
  INV_X0P5B_A12TS_C40 g4542(.A (\mem[5] [3]), .Y (n_4));
  INV_X0P5B_A12TS_C40 g4534(.A (\mem[5] [5]), .Y (n_3));
  BUF_X16M_A12TS_C40 g4536(.A (\data_out[5]_257 ), .Y (data_out[5]));
  INV_X0P5B_A12TS_C40 g4537(.A (\mem[5] [4]), .Y (n_1));
  INV_X0P5B_A12TS_C40 g4526(.A (\mem[1] [1]), .Y (n_0));
  INV_X0P5B_A12TS_C40 g4547(.A (rst_n), .Y (n_130));
  BUFH_X1M_A12TS_C40 drc_buf_sp4697(.A (data_in[0]), .Y (n_231));
  BUFH_X1M_A12TS_C40 drc_buf_sp4707(.A (data_in[7]), .Y (n_242));
  BUFH_X1M_A12TS_C40 drc_buf_sp4717(.A (data_in[6]), .Y (n_253));
  BUFH_X1M_A12TS_C40 drc_buf_sp4727(.A (data_in[5]), .Y (n_264));
  BUFH_X1M_A12TS_C40 drc_buf_sp4737(.A (data_in[4]), .Y (n_275));
  BUFH_X1M_A12TS_C40 drc_buf_sp4747(.A (data_in[3]), .Y (n_286));
  BUFH_X1M_A12TS_C40 drc_buf_sp4757(.A (data_in[2]), .Y (n_297));
  BUFH_X1M_A12TS_C40 drc_buf_sp4767(.A (data_in[1]), .Y (n_308));
endmodule

