
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Feb 13 2026 16:14:05 CST (Feb 13 2026 22:14:05 UTC)

// Verification Directory fv/banyan_cell 

module banyan_cell(x, y, sel, a, b);
  input x, y, sel;
  output a, b;
  wire x, y, sel;
  wire a, b;
  wire n_0, n_32, n_33;
  INV_X0P5B_A12TS_C40 g92(.A (sel), .Y (n_0));
  BUF_X16M_A12TS_C40 drc_bufs(.A (n_33), .Y (b));
  BUF_X16M_A12TS_C40 drc_bufs95(.A (n_32), .Y (a));
  AO22_X1M_A12TS_C40 g2(.A0 (n_0), .A1 (x), .B0 (sel), .B1 (y), .Y
       (n_32));
  AO22_X1M_A12TS_C40 g114(.A0 (n_0), .A1 (y), .B0 (sel), .B1 (x), .Y
       (n_33));
endmodule

